-- 库存表
CREATE TABLE `stock` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '库存ID',
  `product_id` BIGINT NOT NULL COMMENT '商品ID',
  `product_name` VARCHAR(100) NOT NULL COMMENT '商品名称',
  `quantity` INT NOT NULL DEFAULT 0 COMMENT '库存数量',
  `frozen_quantity` INT NOT NULL DEFAULT 0 COMMENT '冻结库存数量',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`)
) COMMENT='库存表';
