# Nacos配置中心示例配置
# Data ID: user-service-dev.yaml
# Group: DEFAULT_GROUP
# 命名空间: dev (可选)

# 应用配置示例
app:
  name: user-service
  version: 1.0.0
  description: 用户服务示例（从 Nacos 读取远程配置）

# 自定义配置示例
custom:
  # 可用于演示 @RefreshScope + @Value 动态刷新
  message: "这是从 Nacos 配置中心读取的 user-service 配置"
  timeout: 3000
  enabled: true

# MyBatis-Plus 配置（从 Nacos 下发）
mybatis-plus:
  # Mapper XML 文件位置（如果有自定义 SQL）
  mapper-locations: classpath*:/mapper/**/*.xml
  # 实体类包路径
  type-aliases-package: com.zxx.learning.common.entity
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 日志实现
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.30.1.125:3306/yunjideploy?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: deploy
    password: NN2mq8*xq



# 日志配置
logging:
  level:
    com.zxx.learning: debug
    org.springframework.cloud: info